foodgram_project/api/urls.py
from django.urls import path, include


urlpatterns = [
    path('v1/', include('api.v1.urls')),
]

foodgram_project/foodgram_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.flatpages import views
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler404, handler500
from django.views.static import serve


urlpatterns = [
    path('about/', include('django.contrib.flatpages.urls')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
]

urlpatterns += [
    path('about-author/', views.flatpage,
         {'url': '/about-author/'}, name='about-author'),
    path('about-spec/', views.flatpage,
         {'url': '/about-spec/'}, name='about-spec'),
    path('api/', include('api.urls')),
    path('', include('mainapp.urls')),

]

handler404 = "foodgram_project.views.page_not_found"  # noqa
handler500 = "foodgram_project.views.server_error"   # noqa

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

urlpatterns += [
    url(r'^static/(?P<path>.*)$', serve,
        {
            'document_root': settings.STATIC_ROOT,
            'show_indexes': settings.DEBUG
        }),
]

foodgram_project/mainapp/models.py
from django.db import models
from django.contrib.auth import get_user_model


User = get_user_model()


class Ingredient(models.Model):
    title = models.CharField(max_length=100)
    dimension = models.CharField(max_length=30)
    description = models.TextField(max_length=200, blank=True, null=True)

    def __str__(self):
        return self.title


class Recipe(models.Model):

    title = models.CharField(max_length=50, db_index=True)
    description = models.TextField(max_length=1000)
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='recipes')

    ingredients = models.ManyToManyField(
        Ingredient,
        related_name='recipes',
        through='RecipeIngredient')
    image = models.ImageField(upload_to='mainapp/', blank=True, null=True)
    pub_date = models.DateTimeField('date published', auto_now_add=True)
    cooking_time = models.PositiveIntegerField(default=1, help_text='(минут)')

    breakfest = models.BooleanField(default=False, verbose_name='Завтрак')
    lunch = models.BooleanField(default=False, verbose_name='Обед')
    dinner = models.BooleanField(default=False, verbose_name='Ужин')

    class Meta:
        ordering = ['-pub_date']

    def __str__(self):
        return self.title


class RecipeIngredient(models.Model):
    ingredient = models.ForeignKey(
        Ingredient,
        on_delete=models.CASCADE,
        related_name='recipe_ingredients')
    recipe = models.ForeignKey(
        Recipe, on_delete=models.CASCADE, related_name='recipe')
    qty = models.PositiveIntegerField(default=1)

    def __str__(self):
        return f'{self.ingredient} {self.qty} {self.ingredient.dimension}'


class Purchase(models.Model):
    buyer = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='purchases')
    recipe = models.ForeignKey(
        Recipe, on_delete=models.CASCADE, related_name='purchases')

    class Meta:
        constraints = [models.UniqueConstraint(
            fields=['buyer', 'recipe'], name='unique purchase')]


class Favorite(models.Model):
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='favorites')
    recipe = models.ForeignKey(
        Recipe, on_delete=models.CASCADE, related_name='favorites')

    class Meta:
        constraints = [models.UniqueConstraint(
            fields=['user', 'recipe'], name='unique favorite')]


class Follow(models.Model):
    consumer = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='consumer')
    cook = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='cook')

    class Meta:
        constraints = [models.UniqueConstraint(
            fields=['consumer', 'cook'], name='unique following')]

foodgram_project/api/v1/views.py
from rest_framework.status import HTTP_201_CREATED
from rest_framework.viewsets import GenericViewSet
from rest_framework.mixins import ListModelMixin
from rest_framework.filters import SearchFilter
from rest_framework.generics import get_object_or_404
from rest_framework.response import Response
from rest_framework.decorators import api_view
from django.contrib.auth import get_user_model

from mainapp.models import Recipe, Ingredient, Purchase, Follow, Favorite
from .serializers import (IngredientSerializer, PurchaseSerializer,
                          FavoriteSerializer, FollowSerializer)


User = get_user_model()


class IngredientListView(ListModelMixin, GenericViewSet):
    queryset = Ingredient.objects.all()
    serializer_class = IngredientSerializer
    filter_backends = [SearchFilter, ]
    search_fields = ['title', ]
    ordering_fields = ['title', ]


@api_view(['POST', 'DELETE'])
def api_purchase_detail(request, recipe_id):
    recipe = get_object_or_404(Recipe, pk=recipe_id)

    if request.method == 'POST':
        serializer = PurchaseSerializer(data=request.data, context={
            'request_user': request.user,
            'request_recipe': recipe})
        serializer.is_valid(raise_exception=True)
        serializer.save(buyer=request.user, recipe=recipe)
        return Response({'success': True}, status=HTTP_201_CREATED)

    if request.method == 'DELETE':
        get_object_or_404(
            Purchase, buyer=request.user, recipe=recipe).delete()

        return Response({'success': True})


@api_view(['POST', 'DELETE'])
def api_favorite_detail(request, recipe_id):
    recipe = get_object_or_404(Recipe, pk=recipe_id)
    if request.method == 'POST':
        serializer = FavoriteSerializer(data=request.data, context={
            'request_user': request.user,
            'request_recipe': recipe})
        serializer.is_valid(raise_exception=True)
        serializer.save(user=request.user, recipe=recipe)
        return Response({'success': True}, status=HTTP_201_CREATED)

    if request.method == 'DELETE':
        get_object_or_404(Favorite, user=request.user, recipe=recipe).delete()
        return Response({'success': True})


@api_view(['POST', 'DELETE'])
def api_follow_detail(request, cook_id):
    cook = get_object_or_404(User, pk=cook_id)
    if request.method == 'POST':
        serializer = FollowSerializer(data=request.data, context={
            'request_consumer': request.user,
            'request_cook': cook})
        serializer.is_valid(raise_exception=True)
        serializer.save(consumer=request.user, cook=cook)
        return Response({'success': True}, status=HTTP_201_CREATED)

    if request.method == 'DELETE':
        get_object_or_404(Follow, consumer=request.user, cook=cook).delete()
        return Response({'success': True})

foodgram_project/templates/DeleteSubmit.html
{% extends "base.html" %}
{% load static %}
{% block title %} Удаление рецепта {% endblock %}
{% block static %}
    <link rel="stylesheet" href="{% static "/pages/index.css" %}">
{% endblock %}
{% block nav %}
    {% include "nav.html"%}
{% endblock %}
{% block content %}
<div class="custom-center-block">
    <p class="custom-text-block"> Удалить рецепт {{ recipe_obj }} ? </p>
    <div class="custom-button-block">
        <form method="post" action="{% url 'recipe_delete' username recipe_obj.pk %}">
            {% csrf_token %}
            <button class="button button_style_light-blue"> Удалить </button>
        </form>
        <form action="{% url 'recipe' username recipe_obj.pk %}" >
            <button class="button button_style_blue"> Отмена </button>
        </form>
    </div>
</div>
{% endblock %}

foodgram_project/templates/authForm.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Войти на сайт</title>
    <link rel="stylesheet" href="./pages/form.css">
</head>
<body class="body">
<header class="header">
    <nav class="nav">
        <div class="nav__container container">
            <ul class="nav__items list">
                <li class="nav__item nav__item_disabled"><a href="#" class="nav__link link">Рецепты</a></li>
                <li class="nav__item nav__item_disabled"><a href="#" class="nav__link link">Список покупок</a></li>
            </ul>
            <ul class="nav__items list">
                <li class="nav__item"><a href="#" class="nav__link link">Войти</a></li>
                <li class="nav__item"><a href="#" class="button button_style_blue">Создать аккаунт</a></li>
            </ul>
        </div>
    </nav>
</header>
<main class="main container">
    <div class="main__header">
        <h1 class="main__title">Войти на сайт</h1>
    </div>
    <div class="form-container">
        <form class="form">
            <div class="form__group">
                <label for="id_username" class="form__label">Имя</label>
                <div class="form__field-group">
                    <input type="text" name="username" id="id_username" class="form__input">
                    <span class="form__error"></span>
                </div>
            </div>
            <div class="form__group">
                <label for="id_password" class="form__label">Пароль</label>
                <div class="form__field-group">
                    <input type="password" name="password" id="id_password" class="form__input">
                    <span class="form__error">Имя пользователя и пароль не совпадают. Введите правильные данные.</span>
                </div>
            </div>
            <div class="form__footer">
                <button class="button button_style_blue">Войти</button>
                <a class="form__forgot-link">Забыли пароль?</a>
            </div>
        </form>
    </div>


</main>
<footer class="footer">
    <div class="footer__container container">
        <a href="#" class="footer__brand link">Продуктовый помощник</a>
        <ul class="footer__items">
            <li class="footer__item"><a href="#" class="footer__link link">Об авторе </a></li>
            <li class="footer__item"><a href="#" class="footer__link link">Технологии</a></li>
        </ul>
    </div>
</footer>
</body>
</html>

foodgram_project/templates/authorRecipe.html
{% extends "base.html" %}
{% block title %}{{ author.username }}{% endblock %}
{% load static %}
{% load user_filters %}
{% block static %}
    <link rel="stylesheet" href="{% static "/pages/index.css" %}">
{% endblock %}
{% block nav %}
    {% include "nav.html" %}
{% endblock %}
{% block content %}    
<div class="main__header">
    <h1 class="main__title">{{ author.username }}</h1>
    {% include "tags.html" with url=request.path food_time=food_time%}
</div>
<div class="author-subscribe" data-author="{{ author.pk }}">
    <p class="card__text">публикаций: {{ recipe_count }}</p>
    <p class="card__text">подписчиков: {{ followers_count }}</p>
    <p></p>
{% if user.is_authenticated and not user == author%}    
    {% if author|is_follow:user %}
        <p style="padding: 0 0 2em 0;"><button class="button button_style_light-blue button_size_subscribe" name="subscribe">Отписаться от автора</button></p>
    {% else %}
        <p style="padding: 0 0 2em 0;"><button class="button button_style_light-blue button_size_subscribe" name="subscribe" data-out>Подписаться на автора</button></p>
    {% endif %}
{% endif %}
</div>
<div class="card-list" >        
    {% for recipe in page %}
        {% include "recipe_item.html" with recipe=recipe %}
    {% endfor %}
</div>
{% if page.has_other_pages %}
    {% include "paginator.html" with items=page paginator=paginator%}
{% endif %}
    
  <script src="{% static "js/components/MainCards.js" %}"></script>

  <script src="{% static "js/components/Purchases.js" %}"></script>
  <script src="{% static "js/components/Favorites.js" %}"></script>
  <script src="{% static "js/components/Subscribe.js" %}"></script>

  <script src="{% static "js/config/config.js" %}"></script>
  <script src="{% static "js/components/AuthorRecipe.js" %}"></script>
  <script src="{% static "js/components/Header.js" %}"></script>

  <script src="{% static "js/api/Api.js" %}"></script>
  <script src="{% static "authorRecipe.js" %}"></script>
{% endblock %}

foodgram_project/templates/base.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %} Заголовок страницы {% endblock %} | Продуктовый помощник </title>
    {% block static %}
    {% endblock %}
</head>
<body class="body">

{% block nav %}
{% endblock %}

<main class="main container">
    {% block content %}         
            <!-- Содержимое страницы -->
    {% endblock content %}    
</main>

<footer class="footer">
        <div class="footer__container container">
            <a href="{% url 'index' %}" class="footer__brand link"> Продуктовый помощник </a>
            <ul class="footer__items">
                <li class="footer__item"><a href="{% url 'about-author' %}" class="footer__link link"> Об авторе </a></li>
                <li class="footer__item"><a href="{% url 'about-spec' %}" class="footer__link link"> Технологии </a></li>
            </ul>
        </div>
    </footer>
</body>
</html>

foodgram_project/templates/favorite.html
{% extends "base.html" %}
{% block title %} Избранное {% endblock %}
{% load static %}
{% block static %}
    <link rel="stylesheet" href="{% static "/pages/index.css" %}">
{% endblock %}
{% block nav %}
    {% include "nav.html" with favorite=True %}
{% endblock %}
{% block content %}
<div class="main__header">
    <h1 class="main__title"> Избранное </h1>
    {% include "tags.html" with url=request.path food_time=food_time%}
</div>

<div class="card-list">
    {% for recipe in page %}
        {% include "recipe_item.html" with recipe=recipe %}
    {% endfor %}
</div>
{% if page.has_other_pages %}
    {% include "paginator.html" with items=page paginator=paginator%}
{% endif %}

<script src="{% static "./js/components/MainCards.js" %}"></script>

<script src="{% static "./js/components/Purchases.js" %}"></script>
<script src="{% static "./js/components/Favorites.js" %}"></script>

<script src="{% static "./js/config/config.js" %}"></script>
<script src="{% static "./js/components/CardList.js" %}"></script>
<script src="{% static "./js/components/Header.js" %}"></script>

<script src="{% static "./js/api/Api.js" %}"></script>
<script src="{% static "favorite.js" %}"></script>
{% endblock %}

foodgram_project/templates/formChangeRecipe.html
{% extends "base.html" %}
{% load static %}
{% load user_filters %}
{% block title %} Редактирование рецепта {% endblock %}
{% block static %}
    <link rel="stylesheet" href="{% static "/pages/form.css" %}">
{% endblock %}
{% block nav %}
    {% include "nav.html" with recipe_add=True %}
{% endblock %}
{% block content %}
    <div class="main__header">
        <h1 class="main__title"> Редактирование рецепта </h1>
    </div>
    <div class="form-container">
        {% include "form_recipe.html" with change=True recipe_id=recipe_obj.pk username=recipe_obj.author%}
    </div>

<script src="{% static "js/config/config.js" %}"></script>
<script src="{% static "js/components/Header.js" %}"></script>
<script src="{% static "js/utils/debouncing.js" %}"></script>
<script src="{% static "js/api/Api.js" %}"></script>
<script src="{% static "formRecipe.js" %}"></script>
{% endblock %}

foodgram_project/templates/formCreateRecipe.html
{% extends "base.html" %}
{% load static %}
{% load user_filters %}
{% block title %} Создание рецепта {% endblock %}
{% block static %}
    <link rel="stylesheet" href="{% static "/pages/form.css" %}">
{% endblock %}
{% block nav %}
    {% include "nav.html" with recipe_add=True %}
{% endblock %}
{% block content %}
    <div class="main__header">
        <h1 class="main__title"> Создание рецепта </h1>
    </div>
    <div class="form-container">
        {% include "form_recipe.html"%}
    </div>

<script src="{% static "js/config/config.js" %}"></script>
<script src="{% static "js/components/Header.js" %}"></script>
<script src="{% static "js/utils/debouncing.js" %}"></script>
<script src="{% static "js/api/Api.js" %}"></script>
<script src="{% static "formRecipe.js" %}"></script>
{% endblock %}

foodgram_project/templates/form_recipe.html
{% load user_filters %}
<form class="form" action="{% if change %}{% url "recipe_edit" username recipe_id %}{% else %}{% url "add_recipe" %}{% endif %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form__group">
        <label for="id_name" class="form__label"> Название рецепта </label>
        <div class="form__field-group">
            {{ form.title|addclass:"form__input" }}
            <span class="form__error"></span>
        </div>
    </div>
    <div class="form__group">
        <p class="form__label">Теги</p>
        <div class="form__field-group">
            <div class="tags">
                <div class="tags__item">
                    {{ form.breakfest|addclass:"tags__checkbox tags__checkbox_style_green" }}
                    <label for="id_breakfast" class="tags__label"> Завтрак </label>
                </div>
                <div class="tags__item">
                    {{ form.lunch|addclass:"tags__checkbox tags__checkbox_style_orange" }}
                    <label for="id_lunch" class="tags__label"> Обед </label>
                </div>
                <div class="tags__item">
                    {{ form.dinner|addclass:"tags__checkbox tags__checkbox_style_purple" }}
                    <label for="id_dinner" class="tags__label"> Ужин </label>
                </div>
            </div>
            <span class="form__error"></span>
        </div>
    </div>
    <div class="form__group">
        <label for="nameIngredient" class="form__label"> Ингредиенты </label>
        <div class="form__field-group">
            <div class="form__field-group-ingredientes">            
                <div class="form__dropdown">
                    <input type="text" id="nameIngredient" class="form__input">                                                
                    <div class="form__dropdown-items"></div>
                </div>
                <input type="number" id="cantidad" class="form__input" min="0">
                <label for="cantidad" class="form__label" id="cantidadVal">шт.</label>
            </div>

            <div class="form__field-group-ingredientes-container">
            {% for i in ingredients_objs %}                        
                <div class="form__field-item-ingredient" id="ing_{{ i.pk }}">                               
                    <span> {{ i.ingredient.title }} {{ i.qty }} {{ i.ingredient.dimension }}</span>
                    <span class="form__field-item-delete"></span>
                    <input id="idIngredient_{{ i }}" name="idIngredient_{{ i }}" type="hidden" value="{{ i.ingredient.id }}">
                    <input id="valueIngredient_{{ i }}" name="valueIngredient_{{ i }}" type="hidden" value="{{ i.qty }}">
                </div>
            {% endfor %}
            </div>
            <span class="form__ingredient-link" id="addIng"> Добавить ингредиент </span>
            <span class="form__error"></span>
            {% if form.non_field_errors %}
                <div class="non-field-errors">
                {% for error in form.non_field_errors %}
                    <p class="form-error">{{ error }}</p>
                {% endfor %}
                </div>
            {% endif %}
            </span>
        </div>
    </div>
    <div class="form__group">
        <label for="id_time" class="form__label"> Время приготовления </label>
        <div class="form__field-group form__field-group_time">            
            {{ form.cooking_time|addclass:"form__input" }}
            <label for="id_time" class="form__label"> минут </label>
            <span class="form__error"></span>
        </div>
    </div>
    <div class="form__group">
        <label for="id_description" class="form__label"> Описание </label>
        <div class="form__field-group">
            {{ form.description|addclass:"form__textarea" }}
            <span class="form__error"></span>
        </div>
    </div>
    <div class="form__group">
        <span class="form__label"> Загрузить фото </span>
        <div class="form__field-group">
            {{ form.image }}
            <span class="form__error"></span>
         </div>
    </div>
    <div class="form__footer">
        <button class="button button_style_blue">{% if change %} Изменить {% else %} Создать рецепт {% endif %}</button>
        {% if change %}
            <a style="margin-left: 2.5em" href="{% url 'recipe_delete' user.username recipe_id %}" class="form__ingredient-link"> Удалить </a>
        {% endif %}
    </div>
</form>

foodgram_project/templates/indexAuth3.html
{% extends "base.html" %}
{% block title %} Рецепты {% endblock %}
{% load static %}
{% block static %}
    <link rel="stylesheet" href="{% static "/pages/index.css" %}">
{% endblock %}

{% block nav %}
    {% include "nav.html" with index=True %}
{% endblock %}

{% block content %}
        <div class="main__header">
            <h1 class="main__title"> Рецепты </h1>
            {% include "tags.html" with url=request.path food_time=food_time%}
        </div>
        <div class="card-list">        
        {% for recipe in page %}
            {% include "recipe_item.html" with recipe=recipe %}
        {% endfor %}
        </div>
    {% if page.has_other_pages %}
        {% include "paginator.html" with items=page paginator=paginator %}
    {% endif %}
  <script src="{% static "js/components/MainCards.js" %}"></script>

  <script src="{% static "js/components/Purchases.js" %}"></script>
  <script src="{% static "js/components/Favorites.js" %}"></script>

  <script src="{% static "js/config/config.js" %}"></script>
  <script src="{% static "js/components/CardList.js" %}"></script>
  <script src="{% static "js/components/Header.js" %}"></script>

  <script src="{% static "js/api/Api.js" %}"></script>
  <script src="{% static "indexAuth.js" %}"></script>  


{% endblock %}

foodgram_project/templates/myFollow.html
{% extends "base.html" %}
{% block title %} Мои подписки {% endblock %}
{% load static %}
{% load user_filters %}
{% block static %}
    <link rel="stylesheet" href="{% static "pages/myFollow.css" %}">
{% endblock %}
{% block nav %}
    {% include "nav.html" with follows=True%}
{% endblock %}
{% block content %}

<div class="main__header">
    <h1 class="main__title"> Мои подписки: {{ cooks_count }}</h1>
</div>
<div class="card-list">
{% csrf_token %}
{% load thumbnail %}
{% for cook in page %}
    <div class="card-user" data-author="{{ cook.pk }}">
    <div class="card-user__header">
    <a href="{% url 'profile' cook.username %}" class="link">
        <h2 class="card-user__title">{{ cook.username }}</h2>
    </a>
    </div>
    <div class="card-user__body">
        <ul class="card-user__items">
        
        {% for recipe in cook|get_recipes %}
            <li class="card-user__item">
            
                <div class="recipe">
                    {% thumbnail recipe.image "250x250" crop="center" upscale=True as im %}
                        <a href="{% url 'recipe' recipe.author.username recipe.id %}" class="link"><img src="{{ im.url }}" alt="Автор рецепта не добавил фото" class="recipe__image"></a>
                    {% endthumbnail %}                    
                    <a href="{% url 'recipe' recipe.author.username recipe.id %}" class="link"><h3 class="recipe__title">{{ recipe.title }}</h3></a>
                    <p class="recipe__text"><span class="icon-time"></span> {{ recipe.cooking_time }} мин.</p>
                </div>
            
            </li>
        {% endfor %}
        {% if cook|get_count_recipes%}
            <li class="card-user__item">
                <a href="{% url 'profile' cook.username %}" class="card-user__link link">{{ cook|get_count_recipes }}</a>
            </li>
        {% endif %}        
        </ul>
    </div>
    <div class="card-user__footer">    
        <button class="button button_style_light-blue button_size_auto" name="subscribe"> Отписаться </button>    
    </div>
    </div>

{% endfor %}
</div>
{% if page.has_other_pages %}
    {% include "paginator.html" with items=page paginator=paginator %}
{% endif %}

<script src="{% static "js/config/config.js" %}"></script>
<script src="{% static "js/components/MainCards.js" %}"></script>
<script src="{% static "js/components/MyFollow.js" %}"></script>
<script src="{% static "js/components/Subscribe.js" %}"></script>
<script src="{% static "js/components/Header.js" %}"></script>
<script src="{% static "js/api/Api.js" %}"></script>
<script src="{% static "myFollow.js" %}"></script>

{% endblock %}

foodgram_project/templates/nav.html
<header class="header">
    <nav class="nav">
        <div class="nav__container container">
            <ul class="nav__items list">
                <li class="nav__item {% if index %}nav__item_active{% endif %}"><a href="{% url 'index'%}" class="nav__link link"> Рецепты </a></li>
                <li class="nav__item {% if follows %}nav__item_active{% endif %}"><a href="{% url 'follows'%}" class="nav__link link"> Мои подписки </a></li>
                <li class="nav__item {% if recipe_add %}nav__item_active{% endif %}"><a href="{% url 'add_recipe' %}" class="nav__link link"> Создать рецепт </a></li>
                <li class="nav__item {% if favorite %}nav__item_active{% endif %}"><a href="{% url 'favorite_list' %}" class="nav__link link"> Избранное </a></li>
                <li class="nav__item {% if purchases %}nav__item_active{% endif %}"><a href="{% url 'purchases_list' %}" class="nav__link link"> Список покупок </a><span class="badge badge_style_blue nav__badge" id="counter">{{ user.purchases.count }}</span></li>
            </ul>
            <ul class="nav__items list">
            {% if user.is_authenticated %}
                <li class="nav__item"><a href="{% url 'profile' user.username %}" class="nav__link link"> Вы вошли как: <p>{{ user.username}}</p></a></li>
                <li class="nav__item"><a href="{% url 'password_change' %}" class="nav__link link"> Изменить пароль </a></li>
                <li class="nav__item"><a href="{% url 'logout' %}" class="nav__link link"> Выход </a></li>
            {% else %}
                <li class="nav__item"><a href="{% url 'login' %}" class="nav__link link"> Войти </a></li>
                <li class="nav__item"><a href="{% url 'signup' %}" class="button button_style_blue"> Создать аккаунт </a></li>
            {% endif %}
            </ul>
        </div>
    </nav>
</header>

foodgram_project/templates/paginator.html
<nav class="pagination" aria-label="Search results pages">
    <ul class="pagination__container">
    {% if page.has_previous %}
        <li class="pagination__item"><a class="pagination__link link" href="?page={{ items.previous_page_number }}{% if food_time %}&filter={{ food_time }}{% endif %}"><span class="icon-left"></span></a></li>
    {% endif %}
    {% for i in paginator.page_range %}
        {% if page.number == i %}
            <li class="pagination__item pagination__item_active"><a class="pagination__link link" href="#">{{ i }}</a></li>
        {% else %}
            <li class="pagination__item"><a class="pagination__link link" href="?page={{ i }}{% if food_time %}&filter={{ food_time }}{% endif %}"> {{ i }} </a></li>
        {% endif %}
    {% endfor %}
    {% if page.has_next %}
        <li class="pagination__item"><a class="pagination__link link" href="?page={{ page.next_page_number }}{% if food_time %}&filter={{ food_time }}{% endif %}"><span class="icon-right"></span></a></li>
    {% endif %}
    </ul>
</nav>

foodgram_project/templates/tags.html
<ul class="tags">
    <li class="tags__item">
    {% if food_time == "breakfest" %}
        <a id="breakfast" class="tags__checkbox tags__checkbox_style_green tags__checkbox_active" href="{{ url }}"></a>
    {% else %}
        <a id="breakfast" class="tags__checkbox tags__checkbox_style_green" href="{{ url }}?filter=breakfest"></a>
    {% endif %}
        <span class="tags__label"> Завтрак </span>
                
    </li>
    <li class="tags__item">
    {% if food_time == "lunch" %}
        <a id="lunch" class="tags__checkbox tags__checkbox_style_orange tags__checkbox_active" href="{{ url }}"></a>
    {% else %}
        <a id="lunch" class="tags__checkbox tags__checkbox_style_orange" href="{{ url }}?filter=lunch"></a>
    {% endif %}
        <span for="lunch" class="tags__label"> Обед </span>
    </li>
    <li class="tags__item">
    {% if food_time == "dinner" %}
        <a id="dinner" class="tags__checkbox tags__checkbox_style_purple tags__checkbox_active" href="{{ url }}"></a>
    {% else %}
        <a id="dinner" class="tags__checkbox tags__checkbox_style_purple" href="{{ url }}?filter=dinner"></a>
    {% endif %}
        <label for="dinner" class="tags__label"> Ужин </label>
    </li>
</ul>